version: '3.7'

services:
    db:
        image: postgres:alpine3.18
        container_name: db
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - pg_volume:/var/lib/postgresql/data
        ports:
            - "5434:5432"
        networks:
            - private

    backend:
        build:
            context: .
        restart: always
        container_name: backend
        ports:
            - 3000:${SERVER_PORT}
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - private
networks:
    private:


volumes:
    pg_volume:
        driver: local
